
version: '3'

services:
  db:
    restart: always
    image: "postgres:15-alpine"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=proposals
      - PORT=1234
    ports:
      - "1234:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:

