server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:1234/postgres
    username: user
    password: pass
    hikari:
      minimum-idle: 10
      maximum-pool-size: 40
      idle-timeout: 10000
      max-lifetime: 3000000
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: false
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.xml
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        sms-output:
          binder: kafka
          content-type: application/json

clients:
  url: localhost:8081

cron: '0 */5 * * * *'

discount:
  defaultDiscount: 5
  birthdayThisMonthDiscount: 10